spring:
  application:
    name: springlens-server

  datasource:
    url: jdbc:postgresql://localhost:5432/springlens
    username: postgres
    password: shreeja

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    open-in-view: false

    properties:
      hibernate:
        ddl-auto: update

        springdoc:
            swagger-ui:
              path: /swagger-ui

            api-docs:
              path: /api-docs

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info